version: '3.6'

services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    volumes:
      - ./data/:/usr/share/elasticsearch/data/:rw 
      - ./elasticsearch-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports: 
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    volumes:
      - ./kibana-config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on: ["elasticsearch"]
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:6.6.1
    ports: 
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes: 
      - ./logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash-config/config:/usr/share/logstash/pipeline:ro
    depends_on: ["elasticsearch"]
